services:
    php:
        build:
            context: .
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%"
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
        volumes:
            - ./app:/app:delegated
        ports:
            - 9000:9000
        depends_on:
            - postgres
        networks:
            - sylius

    nginx:
        image: nginx:1.21-alpine
        command: ["nginx"]
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./app:/app:delegated
        ports:
            - 80:80
        depends_on:
            - postgres
            - php
        networks:
            - sylius

    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - 5432:5432
        networks:
            - sylius

networks:
    sylius:
        driver: bridge
