name: Build Docker Image

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout code
                uses: actions/checkout@v2

            -
                name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            -
                name: install buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    version: latest
            -
                name: build the image
                run: |
                    docker buildx build \
                      --tag ${{ secrets.DOCKER_HUB_USERNAME }}/sylius-image:1.11 \
                      --platform linux/amd64,linux/arm/v7,linux/arm64 .
