name: Build & Publish Docker Image

on:
    push:
        branches:
            - master
            - '1.*'

jobs:
    cd:
        runs-on: ubuntu-latest
        name: CD - build and deploy image
        steps:
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            -
                name: install buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: build and push the image
                run: |
                    docker buildx build \
                        --push \
                        --no-cache \
                        --tag ${{ secrets.DOCKER_HUB_USERNAME }}/sylius-image:1.11 \
                        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 .
