name: Build Docker Image

on:
    push:
        branches-ignore:
            - master
        paths-ignore:
            - '*.md'

jobs:
    ci-traditional:
        strategy:
            matrix:
                platform: [linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8]

        runs-on: ubuntu-latest
        name: CI - Build Traditional Image
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Build Image
                uses: docker/build-push-action@v2
                with:
                    push: false
                    context: "{{defaultContext}}:traditional"
                    tags: sylius-image:cache
                    platforms: ${{ matrix.platform }}
                    cache-to: type=inline
#            -
#                name: Shutdown default MySQL
#                run: sudo service mysql stop
#            -
#                name: Setup MySQL
#                run: |
#                    docker container run \
#                        --platform linux/amd64 \
#                        -e MYSQL_ALLOW_EMPTY_PASSWORD=true \
#                        -p 3306:3306/tcp \
#                        --name mysql \
#                        --net sylius_network \
#                        -d mysql:5.7
            -
                name: Setup Sylius Store
                run: |
                    docker image build \
                        --network sylius_network \
                        --tag sylius-traditional-prod \
                        .github/workflows/

                    docker container run \
                        --net sylius_network \
                        -p 80:80/tcp \
                        -d sylius-traditional-prod
            -
                name: Health Check Store
                run: |
                    sleep 10
                    curl -L --fail http://localhost:80 || exit 1

    ci-headless:
        strategy:
            matrix:
                platform: [linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8]

        runs-on: ubuntu-latest
        name: CI - Build Headless Image
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Build Image
                uses: docker/build-push-action@v2
                with:
                    push: false
                    context: "{{defaultContext}}:headless"
                    platforms: ${{ matrix.platform }}

    ci-experimental:
        strategy:
            matrix:
                platform: [linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8]

        runs-on: ubuntu-latest
        name: CI - Build Experimental Image
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Build Image
                uses: docker/build-push-action@v2
                with:
                    push: false
                    context: "{{defaultContext}}:experimental"
                    platforms: ${{ matrix.platform }}
