name: Build Docker Image

on:
    push:
        branches-ignore:
            - master
        paths-ignore:
            - '*.md'

jobs:
    ci-traditional:
        runs-on: ubuntu-latest
        name: CI - build image
        steps:
            -
                name: Set Up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set Up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Build Image
                uses: docker/build-push-action@v2
                with:
                    push: false
                    context: traditional/.
                    platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8


    ci-headless:
        runs-on: ubuntu-latest
        name: CI - build image
        steps:
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: install buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: build the image
                run: |
                    docker buildx build \
                        --no-cache \
                        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 \
                        headless/.

    ci-experimental:
        runs-on: ubuntu-latest
        name: CI - build image
        steps:
            -
                name: checkout code
                uses: actions/checkout@v2
            -
                name: install buildx
                id: buildx
                uses: crazy-max/ghaction-docker-buildx@v1
                with:
                    buildx-version: latest
            -
                name: build the image
                run: |
                    docker buildx build \
                        --no-cache \
                        --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 \
                        experimental/.
